[Word] (Settings) Add sample for SettingCollection
OfficeDev/office-js-snippets pull request #709
Opened 2022-10-07 21:12 UTC by ElizabethSamuel-MSFT

2022-10-07 21:50 UTC, AlexJerabek requested changes
Some minor requests, but looks good overall.

2022-10-07 21:50 UTC, AlexJerabek commented on samples/word/50-document/manage-settings.yaml
> +                </div>
Small nit, but is it possible to get these text input fields to line up?

![image](https://user-images.githubusercontent.com/38896772/194654427-9423ee28-3d00-4c38-ae50-a165ee1256f4.png)

2022-10-07 21:50 UTC, AlexJerabek commented on samples/word/50-document/manage-settings.yaml
> +            let key = $("#key")
Most of the `let`s should be `const`s in this snippet, since they don't change after initialization.

2022-10-07 21:50 UTC, AlexJerabek commented on samples/word/50-document/manage-settings.yaml
> +            let key = $("#key")
Let's add some "thesis statement" comments to the starts of each of these methods. They'll help the reader both here and in the reference docs once these snippets are plucked over.

2022-10-07 21:50 UTC, AlexJerabek commented on samples/word/50-document/manage-settings.yaml
> +            let setting = settings.add(key, value);
The snippet throws an error for an empty key. Consider adding a check, unless you feel it detracts from the sample too much.

2022-10-07 21:50 UTC, AlexJerabek commented on samples/word/50-document/manage-settings.yaml
> +description: 'This sample shows how to add, get, and delete settings in the file.'
Is it worth defining "settings"? To me, settings are like configurations (zoom, ribbon locking, etc). What's the user scenario?

2022-10-07 21:50 UTC, AlexJerabek commented on samples/word/50-document/manage-settings.yaml
> +            let key = $("#key")
Might be worth noting for the add that adding a setting to an existing key replaces the existing value.

2022-10-07 21:50 UTC, AlexJerabek commented on samples/word/50-document/manage-settings.yaml
> +            if (allSettings.length <= 0) {
Nit since the length can't be less than 0 (and we shouldn't imply otherwise).
```suggestion
            if (allSettings.length == 0) {
```

2022-10-08 00:36 UTC, jipyua commented on samples/word/50-document/manage-settings.yaml
> +        $("#create-setting").click(() => tryCatch(createSetting));
can we change the function name to addSetting instead of createSetting?

2022-10-08 00:39 UTC, jipyua commented on samples/word/50-document/manage-settings.yaml
> +              allSettings.push(setting);
seems no need to define this allSettings variable, directly console.log() each setting value is enough.

2022-10-11 02:56 UTC, jipyua approved these changes

2022-10-11 15:37 UTC, merged