Prepend text on send
OfficeDev/office-js-snippets pull request #738
Opened 2022-11-22 00:40 UTC by ndeleuze

Adding sample for new prependOnSendAsync API

2022-12-21 20:50 UTC, samantharamon requested changes
Thanks for creating this Script Lab snippet, @ndeleuze. It looks great! One minor request. Because the prepend-on-send feature is still in preview, please move the prepend-text-on-send.yaml file to samples/outlook/99-preview-apis. After moving it, please re-run `yarn start` to update the other files. Thanks!

2022-12-21 20:50 UTC, samantharamon commented on samples/outlook/20-item-body/prepend-text-on-send.yaml
> +    Mailbox: '1.9'
```suggestion
    Mailbox: preview
```

2022-12-21 20:50 UTC, samantharamon commented on samples/outlook/20-item-body/prepend-text-on-send.yaml
> +    https://appsforoffice.microsoft.com/lib/1/hosted/office.js
```suggestion  
    https://appsforoffice.microsoft.com/lib/beta/hosted/office.js
```

2022-12-21 20:50 UTC, samantharamon commented on samples/outlook/20-item-body/prepend-text-on-send.yaml
> +order: 7
Please update the order number after moving the file to the preview folder.

2022-12-22 15:43 UTC, ndeleuze commented on samples/outlook/20-item-body/prepend-text-on-send.yaml
> +    Mailbox: '1.9'
Moved👍

2023-01-10 21:21 UTC, samantharamon approved these changes

2023-01-10 21:28 UTC, samantharamon commented
Removing the conceptual article link for now in preparation for the preview announcement during tomorrow's monthly community call. Will re-add the link in a separate PR once the article has been updated.

2023-01-10 21:38 UTC, merged